### ISSUE TITLE
[Fix] 컴포넌트가 여러번 렌더링될 때 중복하여 이벤트 핸들러가 달리는 오류

### ISSUE THREAD

**Issue by Danji-ya** [Elice-in-Wonderland/pro-pro#31]
# Feature Request
- 기능 상세 설명
  - 컴포넌트가 여러번 렌더링될 때 중복하여 이벤트 핸들러가 달리는 오류

[재현과정]
1. 로그인을 합니다.
2. 메인페이지 -> 내가 작성한 게시글 상세 페이지 -> 메인페이지 -> 내가 작성한 게시글 상세 페이지 순서로 라우팅합니다.
3. 위의 과정을 진행후에 북마크를 클릭하면 여러번의 북마크 등록, 해제가 발생합니다.

[원인]
페이지 컴포넌트의 경우에는 container로 넘기는 Element가 root Element로 새로 생성하지 않고 전달해주기 때문에 해당 Element에 중복적으로 이벤트 핸들러가 등록됩니다.

반면에 페이지 컴포넌트의 하위 컴포넌트들은 리렌더링시마다 건내주는 container를 새로 생성하여 전달해주기 때문에 이벤트 핸들러가 매번 새롭게 등록됩니다.

그래서 이와 같은 문제 해결방법을 찾기위해 수요일에 만날 때 이 부분도 같이 의논해보면 좋을 것 같습니다.

**Comment by 5252yabai** [comment]
removeEventListener로 매번 지워주거나, 상세페이지중 최상단인 detailContainer에 이벤트 등록해주는 방법 정도 떠오르네요.

**Comment by Danji-ya** [comment]
> removeEventListener로 매번 지워주거나, 상세페이지중 최상단인 detailContainer에 이벤트 등록해주는 방법 정도 떠오르네요.

detailContainer 방식은 리렌더링 되면 setEvent를 호출하지 않아서 현재로서는 문제가 있을 것 같아요.
removeEventListener 방식도 좋을 것 같은데 이따 만나서 이야기 해보면 좋을 것 같습니다~!!

**Comment by Danji-ya** [comment]
jsx 내부에서 이벤트핸들러를 다실  때 실제 해당 Element에 이벤트리스너를 등록해주기 때문에 해당 요소를 가리키게 됩니다.
그래서 this가 해당 객체를 가리켜 해당 객체의 메서드등을 활용하시려면 this binding이 필요하다는 것을 알고 계시면 좋을 것 같습니다.

```js
newNode.addEventListener(eventType, value);
```


저의 경우에는  React의 클래스 컴포넌트와 유사하게 init()에 해당 객체를 가리키도록 binding을 해주거나 화살표 함수를 활용했습니다.
```js
// bind 함수 활용
class Form extends CustomComponent {
  init() {
    this.handleInputChange = this.handleInputChange.bind(this);
  }

  markup() {
    return (
      <form class="form profile-edit__form" onSubmit={this.props.onSubmit}>
        <!-- 생략 ... -->
      </form>
    );
  }
}

// 화살표 함수 활용
class Form extends CustomComponent {
  markup() {
    return (
      <form class="form profile-edit__form" onSubmit={e => this.props.onSubmit(e)}>
        <!-- 생략 ... -->
      </form>
    );
  }
}
```
