### ISSUE TITLE
[Fix] Axios 응답전 페이지 이동시, 응답후 이전 페이지로 돌아가는 현상

### ISSUE THREAD

**Issue by 5252yabai** [Elice-in-Wonderland/pro-pro#36]
### 예시코드
  ```javascript
  async getPostInfo() {
    const {
      data: { data },
    } = await axiosInstance.get(`/posts/${this.state.postId}`);

    this.setState({
      ...this.state,
      ...data,
      isLoading: false,
      userType: this.findUserType(data.author._id),
    });
  }
  ```
### 상황
상세페이지, 메인페이지, 프로필페이지에서 데이터를 받아온뒤 setState를 실행해 다시 렌더링하고 있습니다. 그런데 요청을 보낸뒤 응답을 받기 전에 페이지를 이동하면 현재 달라진 페이지에서 setState 작업을 하기 때문에 이전 페이지로 돌아가는등의 오류가 발생하고 있습니다. 

예를 들어 프로필페이지 에서 응답이 종료되기전에 메인페이지로 이동한다면, 기존 응답이 종료됬을때 다시 프로필 페이지로 이동하게 됩니다. 정확히는 URL은 메인페이지 그대로고, DOM만 프로필페이지로 교체됩니다.

## 시도할 것
어떻게 해결할지 논의해보면 좋을 것 같습니다. 당장 생각나는 건 다음과 같습니다.
1. 데이터 응답이 끝났을때, 현재 무슨 페이지인지 상태를 파악하고 페이지와 데이터가 일치할때만 setState를 호출한다.
    - 구체적으로 파악할 방법으로는, URL, 최상위 컨테이너의 클래스명 정도 생각납니다.
2. 페이지가 변경되면 요청을 취소한다.
    - https://blog.woolta.com/categories/3/posts/205
    - https://axios-http.com/kr/docs/cancellation

**Comment by Danji-ya** [comment]
언급하신 내용 중 AbortController를 사용하여 요청을 취소해봤습니다.
일단, 제가 알고 있는 두가지 상황은 정상적으로 처리되는 것을 확인을 했는데 혹시 더 좋은 방식이 있으면 같이 의논해보면 좋을 것 같습니다.
- 프로필페이지에서 요청 중에 다른 페이지로 갔을 때 다시 프로필페이지 이동되는 것 방지 확인
- 상세페이지에서 요청 중에 메인 페이지로 갔을 때 다시 상세페이지 이동되는 것 방지 확인

일단 제가 구현방식은 다음과 같습니다.
[구현 방식]
AbortController를 관리할 수 있는 컨트롤 역할의 클래스를 우선 작성하였습니다.

```js
class WebRequestController {
  constructor() {
    this._abortController = new AbortController();
  }

  resetController() {
    this._abortController = new AbortController();
  }

  getController() {
    return this._abortController;
  }
}

export default new WebRequestController();
```
페이지 이동간에 axios 요청을 취소해주기 위해 Router에서 관리하고자 하였고 기존에 axios 요청이 있다면 취소하고 새로운 AbortController 객체를 생성하여 다음 페이지에서 axios를 추적할 수 있도록 리셋하는 방식을 사용하였습니다.


```js
route() {
   // 생략..
    if (webRequestController) {
      webRequestController.getController().abort();
      webRequestController.resetController();
    }
   // 생략...
 }
```

그러면 이제 각 페이지에서 api 통신을 하는 부분에서  signal 옵션을 활성화해서 추적만 해주면 페이지 이동이 되었을 때 기존의 추적중인 axios 요청을 취소할 수가 있었습니다.

다만, axios 취소 요청이 error로 빠지기 때문에 error 핸들링으로 취소일때는 아무런 처리를 하지 않도록 처리해야했습니다. 

```js
async mounted() {
    try {
      const {
        data: { profile },
      } = await axiosInstance.get('/users', {
        withCredentials: true,
        signal: webRequestController.getController()?.signal, // 추적할 수  있는 signal를 주입
      });

      this.setState({
        ...this.state,
        ...profile,
      });
    } catch (error) {
      if (isCanceledRequest(error)) return;

      new Toast({ content: '프로필 정보 불러오기 실패', type: 'fail' });
    }
  }
  
  //export function isCanceledRequest(error) {
 //   return axios.isCancel(error);
 // }
```

**Comment by Danji-ya** [comment]
추가하여 에러 핸들링시에  axios interceptors response로 중간에서 필요한 작업을 하고 Error 객체를 반환대신에 Promise Object를 넘기도록 수정하였습니다.

공식문서에도  Promise.reject를 활용하고 있고 Error 객체를 반환하면 다음과 같이 한번 더 감싸는 단점이 있었습니다.

[좌 - 변경전, 우 - 변경후]

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/53927959/168209983-e1b9fc01-cb78-445a-a37d-b3695f759e08.png">



[수정내용]

```js
axiosInstance.interceptors.response.use(
  response => {
    return response;
  },
  async error => {
   // 중간에러 처리

    return new Error(error); // 변경 전
    return Promise.reject(error); // 변경 후
  },
);
```
[참고자료]
- https://axios-http.com/docs/interceptors
